// Template dokumen resmi: Surat Tugas, SPD (depan-belakang), Laporan, Tanda Terima
const IMG=u=>{u=String(u||'').trim();const m=u.match(/[-\w]{25,}/);return /drive\.google\.com/.test(u)&&m?`https://lh3.googleusercontent.com/d/${m[0]}`:u};
const LG=`<img class="lgo" src="${LOGO}" alt="" onerror="if(!this.dataset.f){this.dataset.f=1;this.src='img/logo.png'}else this.style.visibility='hidden'">`;
const kop=()=>`<div class="kop2">${LG}<div><b>PEMERINTAH KABUPATEN TASIKMALAYA<br>KECAMATAN PUSPAHIANG<br><span class="big2">DESA PUSPAHIANG</span><br><span class="sm">Jln. Raya Puspahiang No. 90 email: desapuspahiang@gmail.com<br>Puspahiang - Tasikmalaya - Kode Pos 46472</span></b></div></div>`;
const hari=d=>new Date(d).toLocaleDateString('id-ID',{weekday:'long'}),rng=(a,b,f)=>a===b?f(a):f(a)+' s.d. '+f(b);
const PK=p=>{const a=String(p.pengikut||'').split(/[,;\n]+/).map(s=>s.trim()).filter(Boolean);return Array.from({length:Math.max(2,a.length)},(_,i)=>['',`${i+1}. ${(a[i]||'').toUpperCase()}`,''])};
const orang=p=>{const M=S.aparatur||[],pk=pkList(p),n=1+pk.length,rc=(()=>{try{return JSON.parse(p.rincian||'[]')}catch(e){return[]}})(),tot=Number(p.realisasi||0),base=Math.floor(tot/n),jm=i=>rc.length===n?rc[i]:(i===0?tot-base*(n-1):base);
 return[{nama:p.nama,jabatan:p.jabatan,nipd:p.nipd,nik:p.nik,jml:jm(0)}].concat(pk.map((x,i)=>{const a=M.find(m=>String(m.nama).toLowerCase()===x.toLowerCase())||{};return{nama:a.nama||x,jabatan:a.jabatan||'',nipd:a.nipd||'',nik:a.nik||'',jml:jm(i+1)}}))};
const kvt=R=>'<table class="kv in">'+R.map(([a,b])=>`<tr><td>${a}<td>: ${esc(b)}`).join('')+'</table>';
const ttdK=(t,x='')=>`<div class="ttd">${t}<br>Kepala Desa Puspahiang,${x}<br><br><br><br><b><u>${PROFIL.kades}</u></b></div>`;

const docST=p=>doc(`<div class="pg ser">${kop()}<h3 class="c ul">SURAT TUGAS</h3><p class="c"><b>Nomor : ${esc(p.no_st)}</b></p><table class="kv"><col style="width:20%"><col style="width:3%"><col><tr><td>DASAR<td>:<td>${esc(p.dasar)}<tr><td colspan="3" class="c"><br><b>MENUGASKAN</b><tr><td>Kepada<td>:<td>${(()=>{const O=orang(p);return O.length>1?O.map((x,i)=>`<div><b>${i+1}.</b></div>`+kvt([['Nama',x.nama],['NIK',x.nik||'-'],['NIPD',x.nipd||'-'],['Jabatan',x.jabatan||'-']])).join(''):kvt([['1. Nama',p.nama],['2. NIK',p.nik||'-'],['3. NIPD',p.nipd||'-'],['4. Jabatan',p.jabatan||'-']])})()}<tr><td>Untuk<td>:<td>1. Menghadiri ${esc(p.maksud)}${kvt([['Hari',rng(p.berangkat,p.kembali,hari)],['Tanggal',rng(p.berangkat,p.kembali,tgl)],['Waktu',p.waktu||'Sesuai undangan'],['Tempat',p.lokasi]])}2. Segala biaya yang timbul dibebankan pada APBDesa<br>3. Melaporkan hasil pelaksanaan tugas kegiatan tersebut kepada Kepala Desa Puspahiang</table><p>Alat angkut yang digunakan: <i>Kendaraan Dinas.</i></p><p>Demikian untuk dilaksanakan dengan penuh tanggung jawab</p>${ttdK('Puspahiang, '+tgl(p.tgl_st||new Date()))}<p class="sm">Tembusan disampaikan kepada:<br>1. Yth. Ketua BPD Desa Puspahiang<br>2. Arsip</p></div>`);

const docSPD=p=>{const n=days(p.berangkat,p.kembali),th=new Date(p.berangkat).getFullYear(),no=p.no_sppd||`SPD/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/${th}`,tg=tgl(p.tgl_st||new Date());
 const R=[['1.','Pejabat yang memberi perintah','Kepala Desa Puspahiang'],['2.','Nama pegawai yang diperintah',p.nama],['3.','a. Pangkat dan Golongan',p.golongan||'-'],['','b. Jabatan/Instansi',(p.jabatan||'-')+' / Pemerintah Desa Puspahiang'],['','c. Tingkat menurut peraturan perjalanan','-'],['4.','Maksud Perjalanan Dinas',p.maksud],['5.','Alat angkut yang dipergunakan','Kendaraan Dinas'],['6.','a. Tempat berangkat','Puspahiang'],['','b. Tempat tujuan',p.lokasi],['7.','a. Lamanya Perjalanan Dinas',`${n} (${tb(n).trim()}) hari`],['','b. Tanggal berangkat',tgl(p.berangkat)],['','c. Tanggal harus kembali',tgl(p.kembali)],['8.','Pengikut:',''],...PK(p),['9.','Pembebanan Anggaran',''],['','a. Instansi','Pemerintah Desa Puspahiang'],['','b. Mata Anggaran',p.mata_anggaran||'-'],['10.','Keterangan lain-lain','']];
 const dt='<td class="dt">&nbsp;',
  Lk=x=>`<table class="kv"><col style="width:12%"><col style="width:34%"><col style="width:5%"><col><tr><td>${x}<td>Tiba di<td>:${dt}<tr><td><td>Pada Tanggal<td>:${dt}</table>`,
  Rk=`<table class="kv"><col style="width:42%"><col style="width:5%"><col><tr><td>Berangkat dari<td>:${dt}<tr><td>Ke<td>:${dt}<tr><td>Pada tanggal<td>:${dt}</table>`,
  sg='<div><div class="sgl"></div>NIP.</div>',
  mid=['I','II','III'].map(x=>`<tr><td><div class="fx"><div>${Lk(x)}</div>${sg}</div><td><div class="fx"><div>${Rk}</div>${sg}</div>`).join('');
 doc(`<div class="pg spd pb">${kop()}<table class="kv in" style="width:46%;margin-left:54%"><tr><td>Lembar ke<td>: I<tr><td>Kode No<td>: ........................<tr><td>Nomor<td>: ${no}</table><h3 class="c ul">SURAT PERJALANAN DINAS (SPD)</h3><table class="bd"><col style="width:7%"><col style="width:38%"><col>${R.map(r=>`<tr><td class="c">${r[0]}<td>${esc(r[1])}<td>${esc(r[2])}`).join('')}</table><div class="ttd" style="text-align:left">Dikeluarkan di : Puspahiang<br>Pada tanggal : ${tg}<br><br>KEPALA DESA PUSPAHIANG,<br><br><br><br><b><u>${PROFIL.kades}</u></b></div></div>
<div class="pg spd"><table class="kv" style="width:56%;margin-left:44%"><col style="width:46%"><col style="width:5%"><col><tr><td>SPD No.<td>:<td>${no}<tr><td>Berangkat dari (tempat kedudukan)<td>:<td>Puspahiang<tr><td>Pada tanggal<td>:<td>${tgl(p.berangkat)}<tr><td>Ke<td>:<td>${esc(p.lokasi)}</table><p style="margin:.7rem 0 .9rem 44%">(Pejabat Pelaksana Teknis Kegiatan)<br><br><br><br><b>(${PROFIL.pptk})</b></p><table class="bx2"><col style="width:50%"><col>${mid}<tr><td><td><div class="fx" style="min-height:150px"><div><table class="kv"><col style="width:46%"><col style="width:5%"><col><tr><td>IV. Tiba kembali di<td>:<td>Puspahiang<tr><td>Pada tanggal<td>:${dt}</table><p>Telah diperiksa, dengan keterangan bahwa perjalanan tersebut diatas benar dilakukan atas perintahnya dan semata-mata untuk kepentingan jabatan dalam waktu yang sesingkat-singkatnya.</p></div><div>KEPALA DESA PUSPAHIANG<br><br><br><b><u>${PROFIL.kades}</u></b></div></div><tr><td colspan="2" style="height:40px">V &nbsp;&nbsp;Catatan Lain-Lain &nbsp;:<tr><td colspan="2" class="sm">VI &nbsp;&nbsp;PERHATIAN:<br>Pejabat yang berwenang menerbitkan SPD, pegawai yang melakukan perjalanan dinas, para Pejabat yang mengesahkan tanggal berangkat/tiba, serta bendahara bertanggung jawab berdasarkan peraturan-peraturan Keuangan Negara apabila Negara menderita rugi akibat kesalahan, kelalaian, dan kealpaannya</table></div>`)};

const docLap=p=>{const L=JSON.parse(p.laporan||'{}'),n=s=>esc(s).replace(/\n/g,'<br>'),ft=(k,f,i)=>`<td>Kegiatan ${i}: ${esc(k||'................')}<td class="c ph">${f?`<img src="${esc(IMG(f))}" alt="">`:'Foto '+i}`;
 doc(`<div class="pg">${kop()}<h3 class="c">LAPORAN HASIL PERJALANAN DINAS</h3><p><b>I. &nbsp;Maksud Perjalanan Dinas.</b><br>${n(L.maksud)}</p><p><b>II. &nbsp;Tujuan Perjalanan Dinas</b><br>${n(L.tujuan)}</p><p><b>III. &nbsp;Waktu, Tempat dan Pelaksanaan</b><br>1. Waktu Pelaksanaan : ${rng(p.berangkat,p.kembali,tgl)}${p.waktu?', '+esc(p.waktu):''}<br>2. Tempat pelaksanaan : ${esc(p.lokasi)}<br>3. Pelaksana : ${esc(p.nama)}${pkList(p).length?'<br>4. Pengikut : '+esc(pkList(p).join(', ')):''}</p><p><b>IV. &nbsp;Hasil /Kesimpulan yang didapat dalam perjalanan dinas sebagai berikut:</b><br>${n(L.hasil)}</p><p><b>V. &nbsp;Foto Dokumentasi</b></p><table class="bd"><col style="width:50%"><col><tr>${ft(L.k1,L.f1,1)}<tr>${ft(L.k2,L.f2,2)}</table><p><b>VI. &nbsp;Penutup</b><br>Demikian laporan perjalanan dinas ini kami buat, sebagai bahan pertanggung jawaban perjalanan Dinas untuk ditindak lanjuti.</p><div class="ttd" style="text-align:left">Puspahiang, ${tgl(new Date())}<br>Pembuat Laporan,${orang(p).map((x,i)=>`<br><br><br><br>${i+1}. Nama : <b><u>${esc(x.nama)}</u></b>`).join('')}</div><div class="ttd" style="margin-top:.5rem">Mengetahui,<br>Kepala Desa Puspahiang<br><br><br><br><b><u>${PROFIL.kades}</u></b></div></div>`)};

const docTT=p=>{const th=new Date(p.berangkat).getFullYear(),tl=p.tgl_lunas||p.kembali,fd=new Date(tl).toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'}),jm=Number(p.realisasi).toLocaleString('id-ID');
 doc(`<div class="pg"><div class="c"><b>TANDA TERIMA PEMBAYARAN BIAYA PERJALANAN DINAS<br>DESA PUSPAHIANG KECAMATAN PUSPAHIANG<br>TAHUN ANGGARAN ${th}</b></div><br><table class="bd tt"><tr><th style="width:6%">No<th>Nama<th>Jabatan<th>NIPD<th>Jumlah (Rp.)<th>Tanda Tangan${orang(p).map((x,i)=>`<tr><td class="c">${i+1}<td>${esc(x.nama)}<td>${esc(x.jabatan||'-')}<td class="n">${esc(x.nipd||'-')}<td class="n r">${x.jml===''?'':Number(x.jml).toLocaleString('id-ID')}<td class="sg">`).join('')}<tr><td colspan="4" style="text-align:right"><b>Jumlah</b><td class="n"><b>${jm}</b><td></table><p>Terbilang : <b>${terbilang(p.realisasi)}</b></p><div class="grid3"><div>Mengetahui<br>Kepala Desa Puspahiang<br><br><br><br><b>${PROFIL.kades}</b></div><div>Lunas Bayar Tgl : ${fd}<br>Kaur Keuangan<br><br><br><br><b>${PROFIL.bendahara}</b><br>NIPD. ${PROFIL.bendaharaNipd}</div><div>Puspahiang, ${tgl(p.kembali)}<br>Pembuat Daftar:<br>Kepala Urusan TU dan Umum<br><br><br><b>${PROFIL.pembuat}</b><br>NIPD. ${PROFIL.pembuatNipd}</div></div></div>`)};
document.querySelectorAll('.lg').forEach(i=>{i.src=LOGO;i.onerror=()=>{i.style.display='none'}});

// Daftar Tanda Terima otomatis (banyak penerima) — format landscape sesuai lampiran
const docTTD=L=>{if(!L.length)return;const th=new Date(L[0].berangkat).getFullYear(),tot=sum(L,'realisasi'),mx=L.map(x=>x.tgl_lunas||x.kembali).sort().pop(),mk=L.map(x=>x.kembali).sort().pop(),fd=new Date(mx).toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'}),f=n=>Number(n).toLocaleString('id-ID');
 doc(`<div class="pg land"><div class="c"><b>TANDA TERIMA PEMBAYARAN BIAYA PERJALANAN DINAS<br>DESA PUSPAHIANG KECAMATAN PUSPAHIANG<br>TAHUN ANGGARAN ${th}</b></div><br><table class="bd tt"><col style="width:5%"><col style="width:20%"><col style="width:24%"><col style="width:22%"><col style="width:12%"><col><tr><th>No<th>Nama<th>Jabatan<th>NIPD<th>Jumlah<br>(Rp.)<th>Tanda Tangan${L.flatMap(orang).map((x,i)=>`<tr><td class="c">${i+1}<td>${esc(x.nama)}<td>${esc(x.jabatan||'-')}<td class="n">${esc(x.nipd||'-')}<td class="n r">${x.jml===''?'':f(x.jml)}<td class="sg">`).join('')}<tr><td><td><td><td><b>Jumlah</b><td class="n r"><b>${f(tot)}</b><td class="sg"></table><p><i><b>Terbilang : ${terbilang(tot)}</b></i></p><div class="grid3"><div>Mengetahui<br>Kepala Desa Puspahiang<br><br><br><br><b>${PROFIL.kades}</b></div><div>Lunas Bayar Tgl : ${fd}<br>Kaur Keuangan<br><br><br><br><b>${PROFIL.bendahara}</b><br>NIPD. ${PROFIL.bendaharaNipd}</div><div>Puspahiang, ${tgl(mk)}<br>Pembuat Daftar:<br>Kepala Urusan TU dan Umum<br><br><br><b>${PROFIL.pembuat}</b><br>NIPD. ${PROFIL.pembuatNipd}</div></div></div>`)};
